### PR TITLE
 Some changes in bot

### PR DESCRIPTION
**Pull request by kesha1225**
Added two services, added param min_length for check func, changed returned by project_exists values to more handy.

### CODE REVIEW

**Comment by prostomarkeloff** [comment]
Minimal length isn't needed i think.

**Comment by jieggii** [comment]
I’m going to review it tomorrow

**Comment by kesha1225** [comment]
> 
> 
> Minimal length isn't needed i think.

Why? Vk service return me "Free" on short project name, but i couldn't create project with same name.

**Comment by prostomarkeloff** [comment]
> > Minimal length isn't needed i think.
> 
> Why? Vk service return me "Free" on short project name, but i couldn't create project with same name.

Because they are reserved.

**Comment by jieggii** [comment]
Oopsie, sry, going to make some rebranding and refactoring...

**Pull request closed without merging**
